version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: "chore(actions)"
    include: "scope"

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "chore(deps)"
    include: "scope"
