import { useCallback, useState } from "react";
import { toast } from "sonner";
import { getModels } from "@/lib/dataService";

/**
 * Arguments passed to the user-supplied execution function.
 */
export interface AIRunContext {
  modelId: string | undefined;
  providerId: string | undefined;
  onLog: (line: string) => void;
}

export interface UseAIRunOptions<T> {
  /**
   * Performs the actual AI request. Receives the selected model/provider and
   * an onLog callback for streaming terminal output. Throws to signal failure.
   */
  execute: (ctx: AIRunContext) => Promise<T>;
  /**
   * Optional toast message shown on success. Receives the result.
   */
  successMessage?: (result: T) => string;
}

export interface UseAIRunReturn<T> {
  selectedModel: string;
  setSelectedModel: (id: string) => void;
  selectedProviderId: string;
  setSelectedProviderId: (id: string) => void;
  loading: boolean;
  terminalLines: string[];
  modelUsed: string;
  result: T | null;
  setResult: (r: T | null) => void;
  run: () => Promise<void>;
  reset: () => void;
}

/**
 * Centralized state + execution machinery shared by AI-driven pages.
 *
 * Owns: model/provider selection, loading flag, streaming terminal lines,
 * the resolved model description (for "Generated by ..." footers), and the
 * try/catch/toast boilerplate. Pages provide the actual request function.
 */
export function useAIRun<T>({ execute, successMessage }: UseAIRunOptions<T>): UseAIRunReturn<T> {
  const [selectedModel, setSelectedModel] = useState("");
  const [selectedProviderId, setSelectedProviderId] = useState("");
  const [loading, setLoading] = useState(false);
  const [terminalLines, setTerminalLines] = useState<string[]>([]);
  const [modelUsed, setModelUsed] = useState("");
  const [result, setResult] = useState<T | null>(null);

  const run = useCallback(async () => {
    setLoading(true);
    setResult(null);
    setTerminalLines([]);

    try {
      const models = await getModels();
      const modelDesc = models.find((m) => m.id === selectedModel)?.description || selectedModel;
      setModelUsed(modelDesc);

      const value = await execute({
        modelId: selectedModel || undefined,
        providerId: selectedProviderId || undefined,
        onLog: (line) => setTerminalLines((prev) => [...prev, line]),
      });

      setResult(value);
      if (successMessage) toast.success(successMessage(value));
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      toast.error(`AI Error: ${msg}`);
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [selectedModel, selectedProviderId, execute, successMessage]);

  const reset = useCallback(() => {
    setResult(null);
    setTerminalLines([]);
    setModelUsed("");
  }, []);

  return {
    selectedModel,
    setSelectedModel,
    selectedProviderId,
    setSelectedProviderId,
    loading,
    terminalLines,
    modelUsed,
    result,
    setResult,
    run,
    reset,
  };
}
