import { useCallback, useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { getModels } from "@/lib/dataService";

// Module-level cache: survives component unmount/remount within a single tab
// session (reset on full page reload). Keyed by the page-supplied `cacheKey`.
interface CachedRun {
  result: unknown;
  terminalLines: string[];
  modelUsed: string;
}
const AI_RUN_CACHE = new Map<string, CachedRun>();

/**
 * Arguments passed to the user-supplied execution function.
 */
export interface AIRunContext {
  modelId: string | undefined;
  providerId: string | undefined;
  onLog: (line: string) => void;
  /** Aborts the request when the page unmounts or a new run starts. */
  signal: AbortSignal;
}

export interface UseAIRunOptions<T> {
  /**
   * Performs the actual AI request. Receives the selected model/provider and
   * an onLog callback for streaming terminal output. Throws to signal failure.
   */
  execute: (ctx: AIRunContext) => Promise<T>;
  /**
   * Optional toast message shown on success. Receives the result.
   */
  successMessage?: (result: T) => string;
  /**
   * If provided, the latest successful run (result + terminal lines + model)
   * is cached in-memory under this key for the lifetime of the tab. Pages
   * that remount on navigation get their previous output back without
   * re-running the model. Pass a stable string per page.
   */
  cacheKey?: string;
}

export interface UseAIRunReturn<T> {
  selectedModel: string;
  setSelectedModel: (id: string) => void;
  selectedProviderId: string;
  setSelectedProviderId: (id: string) => void;
  loading: boolean;
  terminalLines: string[];
  modelUsed: string;
  result: T | null;
  setResult: (r: T | null) => void;
  run: () => Promise<void>;
  reset: () => void;
}

/**
 * Centralized state + execution machinery shared by AI-driven pages.
 *
 * Owns: model/provider selection, loading flag, streaming terminal lines,
 * the resolved model description (for "Generated by ..." footers), and the
 * try/catch/toast boilerplate. Pages provide the actual request function.
 */
export function useAIRun<T>({
  execute,
  successMessage,
  cacheKey,
}: UseAIRunOptions<T>): UseAIRunReturn<T> {
  // Hydrate from the session cache on first render so a page revisit shows the
  // previous output instead of an empty state.
  const cached = cacheKey ? (AI_RUN_CACHE.get(cacheKey) as CachedRun | undefined) : undefined;
  const [selectedModel, setSelectedModel] = useState("");
  const [selectedProviderId, setSelectedProviderId] = useState("");
  const [loading, setLoading] = useState(false);
  const [terminalLines, setTerminalLines] = useState<string[]>(cached?.terminalLines ?? []);
  const [modelUsed, setModelUsed] = useState(cached?.modelUsed ?? "");
  const [result, setResult] = useState<T | null>((cached?.result as T | undefined) ?? null);
  const abortRef = useRef<AbortController | null>(null);

  // Abort any in-flight request when the page unmounts, so abandoned AI runs
  // don't keep the HTTP connection and stream open in the background.
  useEffect(() => {
    return () => abortRef.current?.abort();
  }, []);

  const run = useCallback(async () => {
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    setLoading(true);
    setResult(null);
    setTerminalLines([]);

    try {
      const models = await getModels();
      const modelDesc = models.find((m) => m.id === selectedModel)?.description || selectedModel;
      setModelUsed(modelDesc);

      const collected: string[] = [];
      const value = await execute({
        modelId: selectedModel || undefined,
        providerId: selectedProviderId || undefined,
        signal: controller.signal,
        onLog: (line) => {
          collected.push(line);
          setTerminalLines((prev) => [...prev, line]);
        },
      });

      setResult(value);
      if (cacheKey) {
        AI_RUN_CACHE.set(cacheKey, {
          result: value,
          terminalLines: collected,
          modelUsed: modelDesc,
        });
      }
      if (successMessage) toast.success(successMessage(value));
    } catch (err: unknown) {
      if (controller.signal.aborted) return;
      const msg = err instanceof Error ? err.message : String(err);
      toast.error(`AI Error: ${msg}`);
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [selectedModel, selectedProviderId, execute, successMessage, cacheKey]);

  const reset = useCallback(() => {
    setResult(null);
    setTerminalLines([]);
    setModelUsed("");
    if (cacheKey) AI_RUN_CACHE.delete(cacheKey);
  }, [cacheKey]);

  return {
    selectedModel,
    setSelectedModel,
    selectedProviderId,
    setSelectedProviderId,
    loading,
    terminalLines,
    modelUsed,
    result,
    setResult,
    run,
    reset,
  };
}
