class PromiseScoreValidator:
    """
    Defines configuration and validation rules for the AI-generated "Promise Score".

    This class holds parameters like the number of stocks to analyze and the tolerance for weight validation.
    It provides methods to ensure that the weights generated by the AI for calculating the Promise Score are within acceptable bounds
    and use a predefined set of valid metrics.
    """
    def __init__(self, top_n_stocks: int = 30, weight_tolerance: float = 0.05):
        self.top_n_stocks = top_n_stocks
        self.weight_tolerance = weight_tolerance
        self.min_weight_sum = 1 - self.weight_tolerance
        self.max_weight_sum = 1 + self.weight_tolerance
        
        # Available metrics
        self.available_metrics: list[str] = [
            'Total_Value',
            'Total_Delta_Value',
            'Max_Portfolio_Pct', 
            'Buyer_Count',
            'Seller_Count',
            'Holder_Count', 
            'New_Holder_Count',
            'Net_Buyers',
            'Close_Count'
        ]


    def validate_weights(self, weights: dict) -> bool:
        """
        Validates that the sum of weights is within the defined tolerance.

        The sum of weights must be between `min_weight_sum` and `max_weight_sum`.

        Args:
            weights (dict): A dictionary where keys are metric names and values are their weights.

        Returns:
            bool: True if the sum of weights is valid, False otherwise.
        """
        return self.min_weight_sum <= sum(weights.values()) <= self.max_weight_sum


    def validate_metrics(self, metrics: list) -> list:
        """
        Checks for any metrics that are not in the list of available metrics.

        Args:
            metrics (list): A list of metric names to validate.

        Returns:
            list: A list of invalid metric names. An empty list signifies all metrics are valid.
        """
        return [m for m in metrics if m not in self.available_metrics]
