import math


class PromiseScoreValidator:
    """
    Defines configuration and validation rules for the AI-generated "Promise Score".

    This class holds parameters like the number of stocks to analyze.
    It provides methods to ensure that the weights generated by the AI for calculating the Promise Score are within acceptable bounds
    and use a predefined set of valid metrics.
    """

    AVAILABLE_METRICS: list[str] = [
        "Total_Value",
        "Total_Delta_Value",
        "Max_Portfolio_Pct",
        "Buyer_Count",
        "Seller_Count",
        "Holder_Count",
        "New_Holder_Count",
        "Net_Buyers",
        "Close_Count",
        "Delta",
        "Buyer_Seller_Ratio",
        "High_Conviction_Count",
        "Ownership_Delta_Avg",
        "Portfolio_Concentration_Avg",
    ]

    # Metrics that measure selling pressure: their weights must be negative,
    # every other metric's weight must be positive — a flipped sign would
    # invert the ranking (e.g. rewarding institutional selling).
    NEGATIVE_METRICS: frozenset[str] = frozenset({"Seller_Count", "Close_Count"})

    # The prompt asks for 6-10 metrics: fewer makes the score a near-tie on one
    # axis, more spreads weight across correlated breadth metrics.
    MIN_METRICS: int = 6
    MAX_METRICS: int = 10

    def __init__(self, top_n_stocks: int = 30):
        """
        Stores how many top-ranked stocks the analysis keeps.
        """
        self.top_n_stocks = top_n_stocks

    @staticmethod
    def validate_weight_values(weights: dict[str, float]) -> list[str]:
        """
        Checks that every weight is finite and non-zero and that at least one is positive.

        Args:
            weights (dict): A dictionary where keys are metric names and values are their weights.

        Returns:
            list: Error messages. An empty list signifies all values are valid.
        """
        errors = [
            f"weight for {metric} is not finite and non-zero: {weight}"
            for metric, weight in weights.items()
            if not math.isfinite(weight) or weight == 0
        ]
        if not any(weight > 0 for weight in weights.values() if math.isfinite(weight)):
            errors.append("at least one positive weight is required")
        return errors

    @staticmethod
    def validate_weight_signs(weights: dict) -> list:
        """
        Checks that each weight carries the sign its metric requires.

        Selling metrics (NEGATIVE_METRICS) must have negative weights; every
        other metric must have a positive weight.

        Args:
            weights (dict): A dictionary where keys are metric names and values are their weights.

        Returns:
            list: Metric names whose weight has the wrong sign. An empty list signifies all signs are valid.
        """
        return [
            metric
            for metric, weight in weights.items()
            if (weight >= 0) == (metric in PromiseScoreValidator.NEGATIVE_METRICS)
        ]

    @staticmethod
    def validate_metrics(metrics: list) -> list:
        """
        Checks for any metrics that are not in the list of available metrics.

        Args:
            metrics (list): A list of metric names to validate.
        Returns:
            list: A list of invalid metric names. An empty list signifies all metrics are valid.
        """
        return [m for m in metrics if m not in PromiseScoreValidator.AVAILABLE_METRICS]

    @staticmethod
    def validate_metric_count(weights: dict) -> str:
        """
        Checks that the number of weighted metrics is within MIN_METRICS..MAX_METRICS.

        Args:
            weights (dict): A dictionary where keys are metric names and values are their weights.

        Returns:
            str: An error message, or an empty string when the count is valid.
        """
        count = len(weights)
        if count < PromiseScoreValidator.MIN_METRICS:
            return (
                f"AI returned {count} metrics, fewer than the required minimum of "
                f"{PromiseScoreValidator.MIN_METRICS}"
            )
        if count > PromiseScoreValidator.MAX_METRICS:
            return (
                f"AI returned {count} metrics, more than the allowed maximum of "
                f"{PromiseScoreValidator.MAX_METRICS}"
            )
        return ""


def normalize_weights(weights: dict[str, float]) -> dict[str, float]:
    """
    Scales weights so their absolute values sum to 1, keeping each sign.

    Raises:
        ValueError: If the absolute weights sum to zero.
    """
    total = sum(abs(w) for w in weights.values())
    if total == 0:
        raise ValueError("Cannot normalize weights whose absolute values sum to zero")
    return {metric: w / total for metric, w in weights.items()}
