"""
Generate fresh secrets for a new deployment.

Usage:
    python scripts/generate_secrets.py             # print to stdout
    python scripts/generate_secrets.py --write     # write to .env (refuses to overwrite)
    python scripts/generate_secrets.py --update    # append only the keys that are missing
                                                   # from .env, preserving existing lines.

Each fresh invocation produces brand-new values. Overwriting / replacing an
existing MASTER_KEY without setting MASTER_KEY_PREV first makes already-
encrypted api_keys un-decryptable; that's why `--write` refuses to clobber
and `--update` only fills in the missing keys.

Operational guidance:
- First-time setup: run with `--write`.
- Adding multi-tenant secrets to a `.env` that already has API keys:
  use `--update`.
- Annual KEK rotation: keep current MASTER_KEY as MASTER_KEY_PREV in your
  env, set the new value as MASTER_KEY, run a re-encryption job, then drop
  MASTER_KEY_PREV.
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path

from cryptography.fernet import Fernet


def _fresh_pairs() -> list[tuple[str, str]]:
    """
    Build the env-var key/value pairs. ASCII-only output so Windows
    redirection / clipboard never mangles the values.
    """
    return [
        ("POSTGRES_PASSWORD", secrets.token_urlsafe(32)),
        ("MASTER_KEY", Fernet.generate_key().decode()),
        ("MASTER_KEY_VERSION", "1"),
        ("RESET_PASSWORD_TOKEN_SECRET", secrets.token_urlsafe(32)),
        ("VERIFICATION_TOKEN_SECRET", secrets.token_urlsafe(32)),
    ]


def _render(pairs: list[tuple[str, str]], header: bool = True) -> str:
    """
    Format key/value pairs as dotenv lines.
    """
    lines = []
    if header:
        lines.append("# Generated by scripts/generate_secrets.py - never commit these values.")
    lines.extend(f"{k}={v}" for k, v in pairs)
    return "\n".join(lines) + "\n"


def _existing_keys(path: Path) -> set[str]:
    """
    Parse the keys already present in `path`. Comments and blank lines ignored.
    """
    if not path.exists():
        return set()
    keys: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" in stripped:
            keys.add(stripped.split("=", 1)[0].strip())
    return keys


def main() -> None:
    """
    CLI entry point.
    """
    parser = argparse.ArgumentParser(
        description="Generate secrets for a fresh deployment.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--write",
        nargs="?",
        const=".env",
        metavar="PATH",
        help="Write fresh values to PATH (default: .env). Refuses to overwrite.",
    )
    mode.add_argument(
        "--update",
        nargs="?",
        const=".env",
        metavar="PATH",
        help="Append only the keys that are MISSING from PATH (default: .env). "
        "Existing keys are preserved untouched.",
    )
    args = parser.parse_args()

    pairs = _fresh_pairs()

    if args.write:
        path = Path(args.write)
        if path.exists():
            sys.stderr.write(
                f"ERROR: {path} already exists. Use --update to fill in missing keys, "
                "or move/delete the file first.\n"
            )
            sys.exit(1)
        path.write_text(_render(pairs), encoding="utf-8")
        sys.stderr.write(f"Wrote {path} ({path.stat().st_size} bytes).\n")
        return

    if args.update:
        path = Path(args.update)
        present = _existing_keys(path)
        missing = [(k, v) for k, v in pairs if k not in present]
        if not missing:
            sys.stderr.write(f"{path} already contains all required keys. Nothing to do.\n")
            return
        # Append a separator + only the missing pairs.
        with path.open("a", encoding="utf-8") as f:
            f.write("\n# Added by scripts/generate_secrets.py --update\n")
            f.write(_render(missing, header=False))
        sys.stderr.write(
            f"Appended {len(missing)} missing key(s) to {path}: "
            f"{', '.join(k for k, _ in missing)}\n"
        )
        return

    sys.stdout.write(_render(pairs))


if __name__ == "__main__":
    main()
