"""
Render the single coding-agent manifest (.agents/agents.json) into each agent's
own configuration folder: .claude/, .codex/, .gemini/, .cursor/ and the skill
mirrors under .claude/skills and .github/skills.

The rendered files are generated: edit .agents/ and re-run. `--check` exits 1
when any rendered file differs from what the manifest produces (CI, pre-commit).
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = Path(".agents/agents.json")
SKILLS = Path(".agents/skills")
# Codex reads .agents/skills natively; these agents need a copy.
SKILL_MIRRORS = (Path(".claude/skills"), Path(".github/skills"))

_GENERATED_TOML_HEADER = "# Generated by scripts/sync_agent_configs.py from .agents/agents.json.\n"


def _dump_json(data: object) -> str:
    """
    Serialize JSON the way every rendered file is written.
    """
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def _shell_hooks(manifest: dict) -> list[dict]:
    """
    Return the manifest's hooks that run before a shell command.
    """
    return [h for h in manifest.get("hooks", []) if h["event"] == "pre-shell"]


def _command(hook: dict, root_expr: str, fmt: str) -> str:
    """
    Build the shell command that runs a shared hook script for one agent.
    """
    path = f"{root_expr}/{hook['script']}" if root_expr else hook["script"]
    return f'python "{path}" --format {fmt}'


def _claude(manifest: dict) -> str:
    """
    Render .claude/settings.json: the hooks plus any extra Claude settings.
    """
    settings: dict = {"$schema": "https://json.schemastore.org/claude-code-settings.json"}
    settings.update(manifest.get("claude", {}).get("settings", {}))
    hooks = [
        {
            "type": "command",
            "command": _command(h, "$CLAUDE_PROJECT_DIR", "claude"),
            "timeout": h["timeout_seconds"],
        }
        for h in _shell_hooks(manifest)
    ]
    if hooks:
        settings["hooks"] = {"PreToolUse": [{"matcher": "Bash|PowerShell", "hooks": hooks}]}
    return _dump_json(settings)


def _codex_hooks(manifest: dict) -> str:
    """
    Render .codex/hooks.json; paths resolve from the git root, as Codex recommends.
    """
    hooks = [
        {
            "type": "command",
            "command": _command(h, "$(git rev-parse --show-toplevel)", "codex"),
            "timeout": h["timeout_seconds"],
        }
        for h in _shell_hooks(manifest)
    ]
    return _dump_json({"hooks": {"PreToolUse": [{"matcher": "^Bash$", "hooks": hooks}]}})


def _toml_value(value: object) -> str:
    """
    Format a scalar as TOML; json.dumps covers strings, booleans and numbers.
    """
    return json.dumps(value)


def _codex_config(manifest: dict) -> str:
    """
    Render .codex/config.toml from the manifest's flat `codex` table.
    """
    lines = [_GENERATED_TOML_HEADER.rstrip("\n")]
    tables: dict[str, dict] = {}
    for key, value in manifest.get("codex", {}).items():
        if isinstance(value, dict):
            tables[key] = value
        else:
            lines.append(f"{key} = {_toml_value(value)}")
    for name, table in tables.items():
        lines.append(f"\n[{name}]")
        lines.extend(f"{key} = {_toml_value(value)}" for key, value in table.items())
    return "\n".join(lines) + "\n"


def _gemini(manifest: dict) -> str:
    """
    Render .gemini/settings.json: AGENTS.md as context plus the hooks (timeouts in ms).
    """
    settings: dict = {"context": {"fileName": [manifest["instructions"]]}}
    hooks = [
        {
            "name": h["name"],
            "type": "command",
            "command": _command(h, "$GEMINI_PROJECT_DIR", "gemini"),
            "timeout": h["timeout_seconds"] * 1000,
        }
        for h in _shell_hooks(manifest)
    ]
    if hooks:
        settings["hooks"] = {"BeforeTool": [{"matcher": "run_shell_command", "hooks": hooks}]}
    return _dump_json(settings)


def _cursor(manifest: dict) -> str:
    """
    Render .cursor/hooks.json; Cursor runs project hooks from the repo root.
    """
    hooks = [
        {"command": _command(h, "", "cursor"), "timeout": h["timeout_seconds"]}
        for h in _shell_hooks(manifest)
    ]
    return _dump_json({"version": 1, "hooks": {"beforeShellExecution": hooks}})


def _skill_files(root: Path) -> dict[str, bytes]:
    """
    Map every mirrored skill file (repo-relative POSIX path) to its source bytes.
    """
    files: dict[str, bytes] = {}
    source = root / SKILLS
    if not source.is_dir():
        return files
    for path in sorted(p for p in source.rglob("*") if p.is_file()):
        rel = path.relative_to(source)
        for mirror in SKILL_MIRRORS:
            files[(mirror / rel).as_posix()] = path.read_bytes()
    return files


def render(root: Path) -> dict[str, bytes]:
    """
    Return every generated file as {repo-relative POSIX path: content}.
    """
    manifest = json.loads((root / MANIFEST).read_text(encoding="utf-8"))
    rendered = {
        ".claude/settings.json": _claude(manifest),
        ".codex/hooks.json": _codex_hooks(manifest),
        ".codex/config.toml": _codex_config(manifest),
        ".gemini/settings.json": _gemini(manifest),
        ".cursor/hooks.json": _cursor(manifest),
    }
    files = {path: text.encode("utf-8") for path, text in rendered.items()}
    files.update(_skill_files(root))
    return files


def _mirrored_on_disk(root: Path) -> set[str]:
    """
    List the files currently inside the skill mirror folders.
    """
    found: set[str] = set()
    for mirror in SKILL_MIRRORS:
        base = root / mirror
        if base.is_dir():
            found.update(p.relative_to(root).as_posix() for p in base.rglob("*") if p.is_file())
    return found


def check(root: Path = REPO_ROOT) -> list[str]:
    """
    Return the repo-relative paths whose content differs from the manifest's rendering.
    """
    expected = render(root)
    drift = [
        path
        for path, content in expected.items()
        if not (root / path).is_file() or (root / path).read_bytes() != content
    ]
    drift.extend(sorted(_mirrored_on_disk(root) - expected.keys()))
    return drift


def sync(root: Path = REPO_ROOT) -> list[str]:
    """
    Write every generated file, prune stale skill copies, and return what changed.
    """
    changed = check(root)
    expected = render(root)
    for mirror in SKILL_MIRRORS:
        shutil.rmtree(root / mirror, ignore_errors=True)
    for path, content in expected.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
    return changed


def main(argv: list[str] | None = None) -> int:
    """
    CLI entry point: sync by default, or verify with --check.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if files are out of date")
    args = parser.parse_args(argv)
    if args.check:
        drift = check()
        for path in drift:
            sys.stderr.write(f"out of date: {path}\n")
        if drift:
            sys.stderr.write("Run `python scripts/sync_agent_configs.py` and commit the result.\n")
        return 1 if drift else 0
    for path in sync():
        sys.stdout.write(f"updated: {path}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
