name: Daily Schedule Filings Fetch

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
  - cron: '0 18 * * *'

jobs:
  daily-fetch-and-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Check out repository code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pipenv'

    - name: Cache pipenv dependencies
      uses: actions/cache@v4
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install dependencies
      run: |
        python -m pip install pipenv
        pipenv install --dev

    - name: Run schedule fetcher script
      run: pipenv run python -m app.jobs.schedule_fetcher
      env:
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}

    - name: Get current date
      id: date
      run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "no_changes=true" >> $GITHUB_OUTPUT
          echo "No changes detected in the data files"
        else
          echo "no_changes=false" >> $GITHUB_OUTPUT
          echo "Changes detected, will create PR"
          git status --porcelain
        fi

    - name: Create Pull Request for any data changes
      if: steps.changes.outputs.no_changes == 'false'
      uses: peter-evans/create-pull-request@v7.0.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: Update schedule filings data (${{ steps.date.outputs.today }})"
        committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        title: "📊 Daily Data Update: Schedule Filings (${{ steps.date.outputs.today }})"
        body: |
          - Automated daily update of schedule filings with **${{ steps.date.outputs.today }}** data.
          - Auto generated by the `daily-schedule-fetch` workflow.
        branch: "automated/daily-schedules"
        delete-branch: true
        labels: "automated pr"
        assignees: "dokson"
        reviewers: "dokson"

    - name: Log completion
      run: |
        if [[ "${{ steps.changes.outputs.no_changes }}" == "true" ]]; then
          echo "✅ Workflow completed - No changes detected"
        else
          echo "✅ Workflow completed - PR created for data changes"
        fi
