name: Daily Filings Fetch

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
  - cron: '0 22 * * *'

jobs:
  daily-fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Check out repository code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pipenv'

    - name: Cache pipenv dependencies
      uses: actions/cache@v4
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev

    - name: Run fetcher script
      run: pipenv run python .github/scripts/fetcher.py
      env:
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}

    - name: Get current date
      id: date
      run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "no_changes=true" >> $GITHUB_OUTPUT
          echo "No changes detected in the data files"
        else
          echo "no_changes=false" >> $GITHUB_OUTPUT
          echo "Changes detected, will commit to update/daily-fetch branch"
          git status --porcelain
        fi

    - name: Commit and push changes to daily-fetch branch
      if: steps.changes.outputs.no_changes == 'false'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b automated/daily-fetch
        git add .
        git commit -m "chore: Update filings data (${{ steps.date.outputs.today }})"
        git push --set-upstream origin automated/daily-fetch --force

    - name: Log completion
      run: |
        if [[ "${{ steps.changes.outputs.no_changes }}" == "true" ]]; then
          echo "✅ Workflow completed - No changes detected"
        else
          echo "✅ Workflow completed - Changes committed to automated/daily-fetch branch"
          echo "📌 Branch: automated/daily-fetch"
          echo "🔗 View changes: https://github.com/${{ github.repository }}/tree/automated/daily-fetch"
        fi
