name: Tests

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install pipenv
        pipenv install --dev

    - name: Run tests
      run: pipenv run python -m unittest discover
      env:
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}