name: Python Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install pipenv
        pipenv install --dev

    # 4. Esegui i test con unittest
    - name: Run tests
      run: pipenv run python -m unittest scraper_test.py