name: Tests

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Cache pipenv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies
        run: |
          retry() {
            local retries=3; local count=0;
            until "$@"; do
              count=$((count + 1));
              if [ $count -lt $retries ]; then
                echo "::warning::Attempt $count failed. Retrying in 15 seconds..." && sleep 15;
              else
                echo "::error::Command failed after $retries attempts." && return 1;
              fi;
            done
          }
          
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv --python $(which python) # Ensure virtualenv is created before installing
          retry pipenv install --dev

      - name: Run tests
        run: pipenv run python -m unittest discover
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}

      - name: Summary
        if: always()
        run: |
          if [[ ${{ job.status }} == 'success' ]]; then
            echo "✅ All tests passed successfully!"
          else
            echo "❌ Some tests failed. Please check the logs above."
            exit 1
          fi
