name: Tests

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Cache pipenv virtualenv
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/virtualenvs
            .venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv virtualenv
          python -m virtualenv .venv
          export PIPENV_VENV_IN_PROJECT=1
          pipenv install --dev

      - name: Run tests
        run: pipenv run python -m unittest discover
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}

      - name: Summary
        if: always()
        run: |
          if [[ ${{ job.status }} == 'success' ]]; then
            echo "✅ All tests passed successfully!"
          else
            echo "❌ Some tests failed. Please check the logs above."
            exit 1
          fi
